variable "name" {}
variable "vpc_id" {}
variable "bastion_sg" {}
variable "key_name" {}
variable "pri_sub1" {}
variable "pri_sub2" {}
variable "pub_sub1" {}
variable "pub_sub2" {}
variable "acm_cert_arn" {}
variable "domain" {}
variable "nexus_ip" {}
variable "nr_key" {}
variable "nr_acct_id" {}
variable "ansible_sg" {}