variable "name" {}
variable "vpc" {}
variable "bastion_sg" {}
variable "keypair" {}
variable "subnet_id" {}
variable "private_key" {}
variable "nexus_ip" {}
variable "nr_key" {}
variable "nr_acc_id" {}